# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dotaservice.protos import DotaService_pb2 as dotaservice_dot_protos_dot_DotaService__pb2


class DotaServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.reset = channel.unary_unary(
        '/DotaService/reset',
        request_serializer=dotaservice_dot_protos_dot_DotaService__pb2.GameConfig.SerializeToString,
        response_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.InitialObservation.FromString,
        )
    self.observe = channel.unary_unary(
        '/DotaService/observe',
        request_serializer=dotaservice_dot_protos_dot_DotaService__pb2.ObserveConfig.SerializeToString,
        response_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.Observation.FromString,
        )
    self.act = channel.unary_unary(
        '/DotaService/act',
        request_serializer=dotaservice_dot_protos_dot_DotaService__pb2.Actions.SerializeToString,
        response_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.Empty.FromString,
        )


class DotaServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def reset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def observe(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def act(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DotaServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'reset': grpc.unary_unary_rpc_method_handler(
          servicer.reset,
          request_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.GameConfig.FromString,
          response_serializer=dotaservice_dot_protos_dot_DotaService__pb2.InitialObservation.SerializeToString,
      ),
      'observe': grpc.unary_unary_rpc_method_handler(
          servicer.observe,
          request_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.ObserveConfig.FromString,
          response_serializer=dotaservice_dot_protos_dot_DotaService__pb2.Observation.SerializeToString,
      ),
      'act': grpc.unary_unary_rpc_method_handler(
          servicer.act,
          request_deserializer=dotaservice_dot_protos_dot_DotaService__pb2.Actions.FromString,
          response_serializer=dotaservice_dot_protos_dot_DotaService__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'DotaService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
