# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protobuf/DotaService.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import protobuf.dota_gcmessages_common_bot_script_pb2
import protobuf.DotaAction_pb2
import protobuf.DotaService_pb2


class DotaServiceBase(abc.ABC):

    @abc.abstractmethod
    async def reset(self, stream):
        pass

    @abc.abstractmethod
    async def step(self, stream):
        pass

    def __mapping__(self):
        return {
            '/dotaservice.DotaService/reset': grpclib.const.Handler(
                self.reset,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobuf.DotaService_pb2.Config,
                protobuf.DotaService_pb2.Observation,
            ),
            '/dotaservice.DotaService/step': grpclib.const.Handler(
                self.step,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobuf.DotaService_pb2.Action,
                protobuf.DotaService_pb2.Observation,
            ),
        }


class DotaServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.reset = grpclib.client.UnaryUnaryMethod(
            channel,
            '/dotaservice.DotaService/reset',
            protobuf.DotaService_pb2.Config,
            protobuf.DotaService_pb2.Observation,
        )
        self.step = grpclib.client.UnaryUnaryMethod(
            channel,
            '/dotaservice.DotaService/step',
            protobuf.DotaService_pb2.Action,
            protobuf.DotaService_pb2.Observation,
        )
