# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: protobuf/DotaService.proto
# plugin: grpclib.plugin.main
import abc

import grpclib.const
import grpclib.client

import protobuf.CMsgBotWorldState_pb2
import protobuf.DotaAction_pb2
import protobuf.DotaService_pb2


class DotaServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Step(self, stream):
        pass

    def __mapping__(self):
        return {
            '/dotaservice.DotaService/Step': grpclib.const.Handler(
                self.Step,
                grpclib.const.Cardinality.UNARY_UNARY,
                protobuf.DotaService_pb2.Action,
                protobuf.DotaService_pb2.Observation,
            ),
        }


class DotaServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Step = grpclib.client.UnaryUnaryMethod(
            channel,
            '/dotaservice.DotaService/Step',
            protobuf.DotaService_pb2.Action,
            protobuf.DotaService_pb2.Observation,
        )
